# Generated by Django 5.2.12 on 2026-03-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Comment',
        ),
    ]
